### ISSUE TITLE
Suggestion: Add descriptions for each section of the CSS.

### ISSUE THREAD

**Issue by josephtkim** [cheddarwolves/TeaCozy#3]
To improve the readability and ease of understanding your CSS code further, consider adding descriptions to each section like so:

```css
/* Location Section */

#locations {
	padding-top: 70px;
	min-height: 500px;
	background-image: url("../images/img-locations-background.jpg");
}

#locations h2 {
	margin-bottom: 15px;
}

.location-items {
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
	align-items: center;
}

.location-item {
	background-color: black;
	width: 300px;
	margin: 0 15px 30px 15px;
}

/* Footer Section */

footer .contact {
	text-align: center;
	height: 200px;
}

footer .copyright {
	text-align: left;
	padding: 0 0 0 20px;
}
```
